[2020-06-03 19:13:23,895] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: hello_world.third_task 2020-06-03T13:39:50.261158+00:00 [queued]>
[2020-06-03 19:13:23,904] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: hello_world.third_task 2020-06-03T13:39:50.261158+00:00 [queued]>
[2020-06-03 19:13:23,905] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 19:13:23,905] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-06-03 19:13:23,905] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 19:13:23,913] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): third_task> on 2020-06-03T13:39:50.261158+00:00
[2020-06-03 19:13:23,915] {standard_task_runner.py:53} INFO - Started process 21654 to run task
[2020-06-03 19:13:23,957] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: hello_world.third_task 2020-06-03T13:39:50.261158+00:00 [running]> shreya-nineleaps
[2020-06-03 19:13:23,973] {taskinstance.py:1145} ERROR - name 'project_id' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/anaconda3/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/hello_world.py", line 49, in third_task
    client = bigquery.Client(project=project_id, credentials=credentials)
NameError: name 'project_id' is not defined
[2020-06-03 19:13:23,974] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=hello_world, task_id=third_task, execution_date=20200603T133950, start_date=20200603T134323, end_date=20200603T134323
[2020-06-03 19:13:33,887] {logging_mixin.py:112} INFO - [2020-06-03 19:13:33,887] {local_task_job.py:103} INFO - Task exited with return code 1
